### ISSUE TITLE
publications recommended citation populating twice

### ISSUE THREAD

**Issue by jafflerbach** [academicpages/academicpages.github.io#10]
Thanks so much for developing this template. I've started using it but see that when you click on a publication, the recommended citation [populates twice on the page](https://academicpages.github.io/publication/2015-10-01-paper-title-number-3). How do we change this so that it only shows up at the bottom similar to your personal website?

**Comment by staeiou** [comment]
Hi @jafflerbach, sorry for the late reply. It shows twice in that example because I also have added the recommended citation as the body of the markdown files (see https://github.com/academicpages/academicpages.github.io/edit/master/_publications/2015-10-01-paper-title-number-3.md). Any text below the variables and the `---` will render as markdown in the page, so if you remove that second recommended citation, it should not show in the publication page.
