### ISSUE TITLE
Unsubscribe to others commits?

### ISSUE THREAD

**Issue by marwa38** [academicpages/academicpages.github.io#1364]
Hello team
Thanks for the great package.
Could you please let me know how to unsubscribe to others committing to academicpages?

![image](https://github.com/academicpages/academicpages.github.io/assets/68851733/6815cd41-1736-4e7e-bd10-ae54c4065e0a)

**Comment by marwa38** [comment]
> Hello team
> 
> Thanks for the great package.
> 
> Could you please let me know how to unsubscribe to others committing to academicpages?
> 
> 
> 
> ![image](https://github.com/academicpages/academicpages.github.io/assets/68851733/6815cd41-1736-4e7e-bd10-ae54c4065e0a)
> 
> 

Please let me know how to unsubscribe to others commits? My email is full with these!!

**Comment by leorjorge** [comment]
I have no idea what's the issue with this project, where most people seem to try to commit directly into the repository instead of forking it for their own pages... You can easily unsubscribe from updates by clicking unwatch in the main page of the repository: 
![image](https://github.com/academicpages/academicpages.github.io/assets/9614302/f9dbc88a-5b95-4b79-a485-23bece1a5fc2)
