### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by BUAAZFK** [academicpages/academicpages.github.io#1912]
![image](https://github.com/academicpages/academicpages.github.io/assets/92039791/6b759f80-abb9-468d-9e1b-1af5e989e99d)

**Comment by BUAAZFK** [comment]
The problem appeared when I submitted a change in local respository.

**Comment by rjzupkoii** [comment]
It's really hard to say what the problem is based upon just the screen shot you provided, although I did notice that you now [have a successful run so](https://github.com/BUAAZFK/buaazfk.github.io/actions) did the problem get resolved? You may also want to try opening up a [new topic in the discussions as well](https://github.com/academicpages/academicpages.github.io/discussions).
