### ISSUE TITLE
How to change homepage when I visit my website?

### ISSUE THREAD

**Issue by Harrypotterrrr** [academicpages/academicpages.github.io#230]
I want to visit CV page instead of `about.md`, I found everywhere in `_config.yml` but failed to find relative option. I also wonder why there is no `index.html` in root directory which used to be the home page of the website.
Thanks for your help.

**Comment by sheim** [comment]
Did you ever fin a solution to this? Can you post it for posterity?

**Comment by bluerxing** [comment]
Hi, I finally figured out how to change the page on XXX.github.io from about.md to cv.md. Here's what I did:

In short, I changed the permalink at the top of the cv.md file from /cv/ to /. I also deleted the about.md file, since I realized that / refers to the root of the GitHub Pages site (i.e., XXX.github.io), and /cv/ would point to XXX.github.io/cv/. So, to make the redirect work, simply update the permalink to match the page you want as the main destination.
like:

```
---
layout: archive
title: "CV"
permalink: /
author_profile: true
redirect_from:
  - /resume
---
```
