### ISSUE TITLE
How to freeze the top pane when scrolling down?

### ISSUE THREAD

**Issue by raam93** [academicpages/academicpages.github.io#339]
Currently, if I scroll down, say my publications page, the top pane is not accessible and I have to scroll up to the top to access different options on the top pane such as CV or portfolio. It would be nice to freeze or lock this pane to always appear at the top even during scrolling, like how the side pane with profile pic renders. May I know if this is already possible? 

Thanks in advance!

**Comment by kennethbunker** [comment]
I am also interested in knowing hot to do this.

**Comment by luccalino** [comment]
Check this diff out: https://github.com/mmistakes/minimal-mistakes/issues/490

Hope it helps, worked just fine for me.

**Comment by wrahool** [comment]
@luccalino thanks! That worked for me too. How did you manage to keep the left sidebar from scrolling? Right now, it scrolls down a bit, and then the frozen navigation pane covers part of my picture.

**Comment by ladylazarus3** [comment]
Yes, this works, but when clicking on anchored text in a page (i.e. https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method), the text is overlaid by the header.  i've tried to add additional scroll padding to the css to accommodate the width of the sticky header without any success.  Have others had more success with this?

**Comment by francescoolivo** [comment]
> Yes, this works, but when clicking on anchored text in a page (i.e. https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method), the text is overlaid by the header. i've tried to add additional scroll padding to the css to accommodate the width of the sticky header without any success. Have others had more success with this?

Did you manage to solve it?

**Comment by PeizhiShi** [comment]
> > Yes, this works, but when clicking on anchored text in a page (i.e. https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method), the text is overlaid by the header. i've tried to add additional scroll padding to the css to accommodate the width of the sticky header without any success. Have others had more success with this?
> 
> Did you manage to solve it?

I tried the following solutions, and solve the problem. Hope it helps.

https://stackoverflow.com/questions/4086107/fixed-page-header-overlaps-in-page-anchors/9618795

**Comment by rjzupkoii** [comment]
So it turns out that Minimal Mistakes, and therefore Academic Pages by extension, is using the jQuery [Smooth Scroll](https://github.com/kswedberg/jquery-smooth-scroll) library, which in turn means that the CSS based `scroll-padding-top` doesn't work since it's being overridden by the JavaScript. Getting anchor links to work correctly required updating the offset for `.smoothScroll` in `_main.js` followed by rebuilding `main.min.js` using npm. Everything appears to be working correctly right now, but npm is giving a lot of deprecated warnings (to be addressed in #1975), but it may also make sense to remove the jQuery library in favor of a more CSS based approach to smooth scrolling.
