### ISSUE TITLE
enabling this repository to be used as a template?

### ISSUE THREAD

**Issue by myroslavarm** [academicpages/academicpages.github.io#408]
Hi,

is it possible for you to make this repository accessible as a template?
Forks are more suitable when the developer intends to make PRs to the original repo and with this the contributions in the fork are not shown in the contribution graph. But it is less applicable when I'm using your code as a baseline for my own project. Hence, there's a feature on github where it's possible to make a repository to be used as a template by others, i.e. this https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository for enabling and this for using https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template.

**Comment by rjzupkoii** [comment]
The repository has been updated to a template, although it might take a bit more time before all of the documentation is updated appropriately.

**Comment by GillesC** [comment]
"Use This Template" Button missing for me. SO, I guess it is no longer available as a template (as mentioned in the README) or?

**Comment by rjzupkoii** [comment]
@GillesC I'm not seeing the button either, but since I'm the repository owner my screen is generally a bit different. You should see something similar to what appears in [GitHub's tutorial for templates](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template).
