### ISSUE TITLE
Talks display issue

### ISSUE THREAD

**Issue by willtm** [academicpages/academicpages.github.io#5]
Hello there,

Thank you for creating and sharing this Jekyll theme!  It is just what I've been looking for.  

I don't now if you can assist me or not but I'm having a challenging time trying to get my talks to display.  Instead of seeing text on my cv.html page, I just see empty bullets.  I would appreciate any troublehshooting hints you might have.

CV webpage
https://willtm.github.io/cv/

Forked repository
https://github.com/willtm/willtm.github.io

All the best,

Will

**Comment by staeiou** [comment]
Hi Will, it looks like a simple fix. Your .md files in the _talks directory have invalid YAML metadata -- that is the section with at the top with the variables, between the three dashes. It looks like there isn't a closing quotation mark for:
```
venue: "Georgia State University, College of Law
```

and possibly having the title include a newline, extending to two lines is messing things up too:
```
title: "Formative Assessment in Law Schools - Discussion and
Evaluation of Available Tools"
```

In the future, you can tell that something is wrong with the YAML because when you look at it in GitHub, it shows the raw text, rather than rendering as a nicely formatted table (as it does in https://github.com/willtm/willtm.github.io/blob/master/_publications/2012-10-01-working-group.md for example).

Feel free to let me know if that works, or if you have any questions. Enjoy!

**Comment by willtm** [comment]
Hello!

Thanks for your help.  The lack of closing quotation marks in the YAML header for my markdown file was the problem and that fixed it.  Working perfectly now.

I don't want to hijack my own thread but do you have any further guides/tutorials on how to use the Jupyter notebooks and Python scripts?  I'm intrigued by the possibility of using them but haven't had much success.

**Comment by staeiou** [comment]
Great! And I think those might be out of date, since I made it for my own site but have made improvements to academicpages since then. Thanks for bringing it to my attention, I've added a new issue added for that in #8

**Comment by willtm** [comment]
Hello!

I think you answered my previous question here https://github.com/academicpages/academicpages.github.io/issues/8.  Since there isn't any ready-made documentation, I may give them another try but I'll adapt if they don't work out.

Thanks, again.

Oh, and I see that you just answered!  Thank you.
