### ISSUE TITLE
"Recommended citation" line appears 2 times

### ISSUE THREAD

**Issue by seralouk** [academicpages/academicpages.github.io#693]
Hi all,

Thanks for this amazing repo. I have been trying to build my personal website and I have one question.

In the .md file of my publication, I have only once included a line for the "Recommended citation".
However, in the website, it appears 2 times one after the other. How can I solve this?

<img width="813" alt="Screenshot 2021-06-30 at 15 07 45" src="https://user-images.githubusercontent.com/25902670/123966041-50a17a80-d9b5-11eb-99d4-2b4e301b2959.png">

![Screenshot 2021-06-30 at 15 07 54](https://user-images.githubusercontent.com/25902670/123966050-5303d480-d9b5-11eb-897b-e27fedac86d9.png)

**Comment by leorjorge** [comment]
I'm having a similar issue, and even the example page at https://academicpages.github.io/publication/2015-10-01-paper-title-number-3, for example, does that. I also would like to hire the second link to the actual paper, keeping only the well formated "download paper here" one.

**Comment by vickyliuliu** [comment]
Hello, I'm encountering a similar problem. Did you finally figure out where the second  "recommended citation" come from and in which file to make the modifications? 

Thanks!

**Comment by rjzupkoii** [comment]
This doesn't appear to have been a bug *per se* since the duplicated recommended citation was due to the `citation` field being rendered along with the `content` field in `_layouts/single.html` which is by design for publications. However, I have updated the example text to clarify what is going on and also moved the citation lower in the page in a smaller font to help improve the page aesthetics.
