### ISSUE TITLE
Change the main page

### ISSUE THREAD

**Issue by kosmylo** [academicpages/academicpages.github.io#700]
How can I change the main page which starts with "academicpages is a ready-to-fork GitHub Pages template for academic personal websites"?

**Comment by geografif** [comment]
edit it in about.md

**Comment by bluerxing** [comment]
Hi, I finally figured out how to change the page on XXX.github.io from about.md to cv.md. Here's what I did:

In short, I changed the permalink at the top of the cv.md file from /cv/ to /. I also deleted the about.md file, since I realized that / refers to the root of the GitHub Pages site (i.e., XXX.github.io), and /cv/ would point to XXX.github.io/cv/. So, to make the redirect work, simply update the permalink to match the page you want as the main destination.
like:

```
---
layout: archive
title: "CV"
permalink: /
author_profile: true
redirect_from:
  - /resume
---
```
