### ISSUE TITLE
Remove underlined space between logo and text for Site Author fields

### ISSUE THREAD

**Issue by shbrainard** [academicpages/academicpages.github.io#820]
_config.yml allows for the definition of a number of Site Author attributes that then appear beneath your profile picture.

On Desktop browsers, when you hover over this text, the links become underlined.

Currently, this underlining includes the space between the logo of the company being linked to (Github, Twitter, etc), and the text itself.  This appears to be a function of the "_includes/author-profile.html" file, e.g.:

`        <li><a href="{{ author.researchgate }}"><i class="fab fa-fw fa-researchgate" aria-hidden="true"></i> ResearchGate</a></li>`

I'd like to remove this underlining if possible, but can't seem to figure out how to do so, but still preserve a space between the logo and the text.

Any suggestions appreciated.

**Comment by jayrobwilliams** [comment]
The simplest way to do this is to add padding to the right of the icon and then remove the space between the icon and the text, e.g., 

`<li><a href="{{ author.researchgate }}"><i class="fab fa-fw fa-researchgate" aria-hidden="true" style="padding-right: 1.5em;"></i>ResearchGate</a></li>`

This still includes a visual space (specified in ems) between the icon and the text, but it won't be underlined because it won't be a textual space. If you want to avoid the trouble of manually changing the spacings for all attributes, you can grab the updated code from my website's repo here: https://github.com/jayrobwilliams/jayrobwilliams.github.io/blob/96ef61491759628eb6c066d5ba72dff218b84939/_includes/author-profile.html.

**Comment by shbrainard** [comment]
Nice!

**Comment by rjzupkoii** [comment]
This is fixed now, I've added a class (`.icon-pad-right` ) under `_sass/_utilities.scss` that will allow you to control the amount of padding. I've also updated the icon for Google Scholar as well.
