### ISSUE TITLE
Update the "_config.yml" file

### ISSUE THREAD

**Issue by aymeric-collart** [academicpages/academicpages.github.io#871]
Hello, 

I apologize for my very "basic" question. I would like to update the "_config.yml" file. I saw the following message in the file:

# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

My understanding is that the update that I did in the file won't be effective until the server process is restarted.
However, I am very new to github, and I have no clue about how to restart the server process. I am using the web interface. But maybe I am just missing something?

Thanks in advance!
Aymeric

**Comment by BenQuigley** [comment]
Hey, if you're using the web interface, you can disregard that. The github.io server is constantly watching your repository for changes, and it restarts its jekyll server process whenever it sees one, so that your site stays up to date. `jekyll serve` is the command that you would type into your command-line interface in the project folder if you wanted to run this site locally, which is a good idea because it lets you test your changes locally before pushing them to the web.

**Comment by wangweiran0129** [comment]
Hello, I am also facing this issue and wanted to know if there is any updated info related to this issue.
